### PR TITLE
to-do-item split from to-do-list

### LINKED ISSUE #3: Code splitting
Split out "todo-item.js" from "todo-list.js", so there are 2 components for it. 
TodoList is responsible for the state of each TodoItem and passes the state down to each item

### PR DESCRIPTION
**Pull request by ArtursKrasts**

### CODE REVIEW

**Comment by oberzs** [comment]
this is not specific for this comment, but remember when i told you to keep all file naming the same. because you changed other files to start with the lowercase letter, you should also change `App.js` to `app.js`

**Comment by ArtursKrasts** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?7DCECE3306EFEE741F31433A78F9D7F37251

**Comment by ArtursKrasts** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?028DD143D4FCCFB680B31AD6CA023A7D1031

**Review by oberzs — APPROVED** [review]
Looks good!

**Pull request merged**
